import Head from 'next/head'
import Home from "@/components/Home";
import {useState} from "react";

export default function Index() {
    const [hide, setHide] = useState(false)
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="flex justify-center">
                <div onClick={() => setHide(!hide)}>hide</div>
                {hide ? <Home/> : <></>}
                <Home/>
                <Home/>
            </main>
        </>
    )
}
